version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "devcyclehq/engineering"
    versioning-strategy: increase
    
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "devcyclehq/engineering"

  - package-ecosystem: composer
    directory: "/proxies/php/php-proxy"
    schedule:
      interval: "daily"
    reviewers:
      - "devcyclehq/engineering"

  - package-ecosystem: npm
    directory: "/proxies/nodejs"
    schedule:
      interval: "daily"
    reviewers:
      - "devcyclehq/engineering"

  - package-ecosystem: pip
    directory: "/proxies/python"
    schedule:
      interval: "daily"
    reviewers:
      - "devcyclehq/engineering"

  - package-ecosystem: gomod
    directory: "/proxies/go"
    schedule:
      interval: "daily"
    reviewers:
      - "devcyclehq/engineering"

  - package-ecosystem: nuget
    directory: "/proxies/dotnet"
    schedule:
      interval: "daily"
    reviewers:
      - "devcyclehq/engineering"

  - package-ecosystem: gradle
    directory: "/proxies/java"
    schedule:
      interval: "daily"
    reviewers:
      - "devcyclehq/engineering"

  - package-ecosystem: npm
    directory: "/proxies/openfeature-nodejs"
    schedule:
      interval: "daily"
    reviewers:
      - "devcyclehq/engineering"

  - package-ecosystem: bundler
    directory: "/proxies/ruby"
    schedule:
      interval: "daily"
    reviewers:
      - "devcyclehq/engineering"
