name: 'DevCycle Test Harness'
description: 'Run test harness tests against given SDKs'
inputs:
  sdk:
    description: 'Which SDK to test'
    required: true
  sdk-version:
    description: 'Which version of the SDK to test. If not specified; defaults to the latest version'
    required: false
  sdk-github-sha:
    description: 'The SHA ref of the SDK to test - used in PRs. If not specified; sdk-version is used'
    required: false

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3.3.0
      with:
        repository: DevCycleHQ/test-harness
        token: ${{ secrets.TEST_HARNESS_GH_SECRET }}
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'yarn'
    - name: Write variables to .env file
      shell: bash
      run: |
        if [ ! -f ".env" ]
        then
         echo "SDK_GITHUB_SHA='${{ env.GITHUB_SHA }}'" >> ".env"
         echo "SDKS_TO_TEST='${{ env.SDKS_TO_TEST }}'" >> ".env"
        fi
    - name: Install Dependencies
      shell: bash
      run: yarn install
    - name: Run All Tests
      shell: bash
      run: yarn test:ci