name: 'DevCycle Test Harness'
description: 'Run test harness tests against given SDKs'
inputs:
  sdks-to-test:
    description: 'Which SDKs to test'
    required: true
  sdk-github-sha:
    description: 'The SHA ref of the SDK to test - used in PRs. If not specified; sdk-version is used'
    required: false
  github-token:
    description: 'The GitHub token to use for the checkout action'
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3.3.0
      with:
        repository: DevCycleHQ/test-harness
        token: ${{ inputs.github-token }}
    - uses: actions/setup-node@v3
      with:
        node-version: 20
        cache: 'yarn'
    - name: Install Dependencies
      shell: bash
      run: yarn install
    - name: Run All Tests
      shell: bash
      run: yarn test:ci
      env:
        SDK_GITHUB_SHA: ${{ inputs.sdk-github-sha }}
        SDKS_TO_TEST: ${{ inputs.sdks-to-test }}

    # TODO: Support PRs from forks with https://github.com/marketplace/actions/test-reporter#recommended-setup-for-public-repositories
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()   # run this step even if previous step failed
      with:
        name: Test Report          # Name of the check run which will be created
        path: jest-*.xml           # Path to test results
        reporter: jest-junit       # Format of test results
