name: 'DevCycle Test Harness'
description: 'Run test harness tests against given SDKs'
inputs:
    sdks-to-test:
        description: 'Which SDKs to test'
        required: true
    sdk-capabilities:
        description: 'Which capabilities to test'
        required: false
    sdk-github-sha:
        description: 'The SHA ref of the SDK to test - used in PRs. If not specified; sdk-version is used'
        required: false
runs:
    using: 'composite'
    steps:
        - uses: actions/checkout@v4
          with:
              repository: DevCycleHQ/test-harness

        - name: 'Install Docker'
          shell: bash
          run: sudo apt install docker-compose

        - name: Enable Corepack
          shell: bash
          run: corepack enable

        - uses: actions/setup-node@v4
          with:
              node-version: 22
              cache: 'yarn'

        - name: Install Dependencies
          shell: bash
          run: yarn install

        - name: Run All Tests
          shell: bash
          run: yarn test:ci
          env:
              SDK_GITHUB_SHA: ${{ inputs.sdk-github-sha }}
              SDKS_TO_TEST: ${{ inputs.sdks-to-test }}
              SDK_CAPABILITIES: ${{ inputs.sdk-capabilities }}

        - uses: actions/upload-artifact@v4
          if: success() || failure()
          with:
              name: test-results
              path: jest-*.xml

        - name: Test Report
          uses: dorny/test-reporter@v1
          if: ${{ github.event.pull_request.head.repo.full_name == github.event.pull_request.base.repo.full_name }} && (success() || failure())
          with:
              name: Test Report # Name of the check run which will be created
              path: jest-*.xml # Path to test results
              reporter: jest-junit # Format of test results

