version: "3.7"

services:
  nodejs:
    build:
      context: ./proxies/nodejs
      args:
        - NODEJS_SDK_VERSION=${NODEJS_SDK_VERSION}
        - SDK_GITHUB_SHA=${SDK_GITHUB_SHA}
        - SDKS_TO_TEST=${SDKS_TO_TEST}
    container_name: nodejs
    ports:
      - "3000"
  python:
    build:
      context: ./proxies/python
      args:
        - PYTHON_SDK_VERSION=${PYTHON_SDK_VERSION}
    container_name: python
    ports:
      - "3000"
  dotnet:
    build:
      context: ./proxies/dotnet
      args:
        - DOTNET_CLOUD_SDK_VERSION=${DOTNET_CLOUD_SDK_VERSION}
        - DOTNET_LOCAL_SDK_VERSION=${DOTNET_LOCAL_SDK_VERSION}
    container_name: dotnet
    ports:
      - "3000"
  java:
    build:
      context: ./proxies/java
      args:
        - JAVA_SDK_VERSION=${JAVA_SDK_VERSION}
    container_name: java
    ports:
      - "3000"
