name: Node.js CI

on:
  workflow_dispatch:
    inputs:
      sdk:
        type: string
        description: The SDK to run the test harness against
      sha:
        type: string
        description: The SHA that triggered this test harness run
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - uses: actions/checkout@v3
    - run: yarn
    - run: yarn test