name: Run Harness Tests
run-name: ${{ github.event.inputs.title }}
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      sdk:
        type: string
        description: The SDK to run the test harness against
      sha:
        type: string
        description: The SHA that triggered this test harness run
      title:
        type: string
        description: The title of the PR that triggered this test harness run


jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Run Tests
    permissions:
      contents: read
      id-token: write
    env:
      DOCKER_HOST_IP: '172.17.0.1'
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: depot/setup-action@v1
      - name: Write variables to .env file
        run: |
          if [ ! -f ".env" ]
          then 
              echo "SDK_GITHUB_SHA='${{ github.event.inputs.sha }}'" >> ".env"
              echo "SDKS_TO_TEST='${{ github.event.inputs.sdk }}'" >> ".env"
          fi
      - name: Install Dependencies
        run: yarn
      - name: Build Docker Images with depot.dev
        uses: depot/bake-action@v1
        with:
          project: p52dtjfn6z
          token: ${{ secrets.DEPOT_TOKEN }}
          platforms: linux/amd64
          load: true
          files: docker-compose.yml
      - name: Run All Tests
        run: yarn test:ci
