name: Node.js CI

on:
  [workflow_dispatch, workflow_call]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - uses: actions/checkout@v3
    - run: yarn
    - run: yarn test